title: Technical blog from misostack
email: misostack.com@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tips, tools for programming, includes : web, ops, app, ...
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.misostack.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  misostack
google_analytics: UA-106909431-1
lang: vi-VN

# Exclude
exclude: [vendor]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
theme: jekyll-theme-cayman

# repo
future: true
repository: misostack/blog
github: [metadata]

# content

collections:
  category:
    output: true
  tag:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: tag
    values:
      layout: "tag"